<a href="https://colab.research.google.com/github/MannCodes14/Pytorch-NeuralNetworks/blob/main/Torch_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [19]:

tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [20]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [21]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a.add(tensor_b)
# here the actual value of tensor_a will not change

tensor([ 6,  8, 10, 12])

In [23]:
tensor_a

tensor([1, 2, 3, 4])

In [14]:
# but using _ after add, the value of the tensor_a will change

# tensor_a.add_(tensor_b)

In [15]:
# tensor_a

In [24]:
#subtratcion

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [26]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [27]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [28]:
# Mul longhand
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [29]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [30]:
tensor_b.div(tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [31]:
#Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [32]:
tensor_b.remainder(tensor_a)

tensor([0, 0, 1, 0])