<a href="https://colab.research.google.com/github/MannCodes14/Pytorch-NeuralNetworks/blob/main/Torch_op.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
#tensors in torch

my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#reshape and view
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
#if we dont know the number of elements then use -1
my_tensor2 = torch.arange(10)
my_tensor2 = my_tensor2.reshape(2,-1)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_tensor2 = torch.arange(10)
my_tensor2 = my_tensor2.reshape(-1,5)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_tensor2 = torch.arange(10)
my_tensor3 = my_tensor2.view(-1,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])